eitri-apps:
- path: ./eitri-shopping-vtex-daisy-shared
  workspace: eitri-shopping-vtex-daisy-shared
  alias: shared
  focus: false
  shared: true
- path: ./eitri-shopping-vtex-daisy-pdp
  workspace: eitri-shopping-vtex-daisy-pdp
  alias: pdp
  focus: false
  shared: false
- path: ./eitri-shopping-vtex-daisy-home
  workspace: eitri-shopping-vtex-daisy-home
  alias: home
  focus: true
  shared: false
- path: ./eitri-shopping-vtex-daisy-checkout
  workspace: eitri-shopping-vtex-daisy-checkout
  alias: checkout
  focus: false
  shared: false
- path: ./eitri-shopping-vtex-daisy-account
  workspace: eitri-shopping-vtex-daisy-account
  alias: account
  focus: false
  shared: false
- path: ./eitri-shopping-vtex-daisy-cart
  workspace: eitri-shopping-vtex-daisy-cart
  alias: cart
  focus: false
  shared: false
application-id: 190f8c0c-4247-403f-b020-668c059201d2
