export { default as HeaderCart } from './components/Header/HeaderCart'
export { default as HeaderComponent } from './components/Header/HeaderComponent'
export { default as HeaderLogo } from './components/Header/HeaderLogo'
export { default as HeaderMenu } from './components/Header/HeaderMenu'
export { default as HeaderSearch } from './components/Header/HeaderSearch'
export { default as HeaderReturn } from './components/Header/HeaderReturn'
export { default as HeaderText } from './components/Header/HeaderText'
export { default as CustomButton } from './components/CustomButton/CustomButton'
export { default as CustomInput } from './components/CustomInput/CustomInput'
export { default as HeaderTemplate } from './components/Header/HeaderTemplate'
export { HEADER_TYPE } from './utils/constants'

export { default as Loading } from './components/Loading/LoadingComponent' 
export { default as Spacing } from './components/Spacing/Spacing'
export { default as Divisor } from './components/Divisor/Divisor'
export { default as ProductCardDefault } from './components/ProductCard/ProductCardDefault'
export { default as ProductCardFullImage } from './components/ProductCard/ProductCardFullImage'
export { default as GenericError } from './components/Error/GenericError'