name: Push and publish Eitri Application

on:
  pull_request:
    types:
      - closed
    branches:
      - develop
      - main

env:
  EITRI_CLI_CLIENT_ID: ${{ secrets.EITRI_CLI_CLIENT_ID }}
  EITRI_CLI_CLIENT_SECRET: ${{ secrets.EITRI_CLI_CLIENT_SECRET }}

  DEV_ENVID: ${{ vars.APP_DEV_ENV_ID }}
  PROD_ENVID: ${{ vars.APP_PRD_ENV_ID }}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR was merged
        run: |
          if [ "${{ github.event.pull_request.merged }}" != "true" ]; then
            echo "❌ PR foi fechado sem merge. Encerrando pipeline."
            exit 0
          fi
          echo "☑️ PR foi mergeado. Continuando pipeline..."

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Eitri CLI
        run: npm install -g eitri-cli

      - name: Install yq v4 locally
        run: |
          mkdir -p $HOME/bin
          curl -L https://github.com/mikefarah/yq/releases/download/v4.43.1/yq_linux_amd64 -o $HOME/bin/yq
          chmod +x $HOME/bin/yq
          echo "$HOME/bin" >> $GITHUB_PATH
          yq --version

      - name: Detect changed Eitri-apps
        id: detect
        run: |
          set -euo pipefail
          trap 'echo "❌ Falha na detecção de eitri-apps alterados!"' ERR

          echo "🔍 Detectando eitri-apps alterados..."

          if [ ! -f app-config.yaml ]; then
            echo "❌ Arquivo app-config.yaml não encontrado na raiz do repositório."
            exit 1
          fi

          CHANGED_SHARED_MODULES=""
          CHANGED_NON_SHARED_MODULES=""

          BASE_SHA=${{ github.event.pull_request.base.sha }}
          HEAD_SHA=${{ github.event.pull_request.head.sha }}

          echo "🔗 Base SHA: $BASE_SHA"
          echo "🔗 Head SHA: $HEAD_SHA"

          CHANGED_FILES=$(git diff --name-only $BASE_SHA $HEAD_SHA)

          echo "📝 Arquivos alterados detectados:"
          echo "$CHANGED_FILES"

          MODULE_PATHS=$(yq eval '.eitri-apps[].path' app-config.yaml)

          echo "📂 Paths configurados no app-config.yaml:"
          echo "$MODULE_PATHS"

          for path in $MODULE_PATHS; do
            NORMALIZED_PATH=$(echo "$path" | sed 's#^./##' | sed 's#/$##')
            echo "🔎 Verificando se $NORMALIZED_PATH foi alterado..."

            MATCH=$(echo "$CHANGED_FILES" | grep -E "^${NORMALIZED_PATH}/" || true)

            if [ -n "$MATCH" ]; then
              echo "☑️ Eitri-app $path alterado."

              IS_SHARED=$(yq eval '.eitri-apps[] | select(.path | sub("^\\./"; "" ) | sub("/$"; "") == "'"$NORMALIZED_PATH"'") | .shared' app-config.yaml || echo "false")
              IS_SHARED=${IS_SHARED:-false}
              echo "🔍 Valor de SHARED para $path: [$IS_SHARED]"

              if [[ "$IS_SHARED" =~ ^[Tt][Rr][Uu][Ee]$ ]]; then
                CHANGED_SHARED_MODULES="$CHANGED_SHARED_MODULES $path"
              else
                CHANGED_NON_SHARED_MODULES="$CHANGED_NON_SHARED_MODULES $path"
              fi
            else
              echo "⚠️ Nenhuma alteração detectada em ./$NORMALIZED_PATH."
            fi
          done

          echo "changed_shared_modules=$CHANGED_SHARED_MODULES" >> $GITHUB_OUTPUT
          echo "changed_non_shared_modules=$CHANGED_NON_SHARED_MODULES" >> $GITHUB_OUTPUT

          echo "☑️ Shared modules alterados: $CHANGED_SHARED_MODULES"
          echo "☑️ Non-shared modules alterados: $CHANGED_NON_SHARED_MODULES"

      - name: Process shared eitri-apps
        if: steps.detect.outputs.changed_shared_modules != ''
        run: |
          set -euo pipefail
          trap 'echo "❌ Falha no processamento dos eitri-apps compartilhados!"' ERR

          SUCCESSFUL_MODULES=""
          FAILED_MODULES=""

          for module in ${{ steps.detect.outputs.changed_shared_modules }}; do
            echo "⚙️ Processando shared eitri-app: $module"

            if [ ! -d "$module" ]; then
              echo "⚠️ Diretório $module não encontrado. Pulando..."
              FAILED_MODULES="$FAILED_MODULES $module"
              continue
            fi

            pushd "$module" > /dev/null

            if [[ "${{ github.base_ref }}" == "main" ]]; then
              ENV_ID="${{ env.PROD_ENVID }}"
            else
              ENV_ID="${{ env.DEV_ENVID }}"
            fi

            echo "🌍 Ambiente selecionado: $ENV_ID"

            echo "🔗 Eitri-app $module é compartilhado. Executando 'eitri push-version --shared'"
            if ! eitri push-version --shared; then
              echo "❌ Falha ao executar push-version --shared no módulo $module"
              FAILED_MODULES="$FAILED_MODULES $module"
              popd > /dev/null
              continue
            fi

            if [[ "${{ github.base_ref }}" == "develop" ]]; then
              echo "🚀 Publicando com 'eitri publish -e $ENV_ID'"
              if ! eitri publish -e $ENV_ID; then
                echo "❌ Falha ao executar publish no módulo $module"
                FAILED_MODULES="$FAILED_MODULES $module"
                popd > /dev/null
                continue
              fi
            else
              echo "⚠️ Publicação desativada, PR não é para develop."
            fi

            SUCCESSFUL_MODULES="$SUCCESSFUL_MODULES $module"

            popd > /dev/null
            echo "✅ Finalizado processamento do shared eitri-app: $module"
          done

          echo "======================================"
          echo "✅ Shared módulos processados com sucesso: $SUCCESSFUL_MODULES"
          echo "❌ Shared módulos que falharam: $FAILED_MODULES"
          echo "======================================"

      - name: Process non-shared eitri-apps
        if: steps.detect.outputs.changed_non_shared_modules != ''
        run: |
          set -euo pipefail
          trap 'echo "❌ Falha no processamento dos eitri-apps não compartilhados!"' ERR

          SUCCESSFUL_MODULES=""
          FAILED_MODULES=""

          for module in ${{ steps.detect.outputs.changed_non_shared_modules }}; do
            echo "⚙️ Processando non-shared eitri-app: $module"

            if [ ! -d "$module" ]; then
              echo "⚠️ Diretório $module não encontrado. Pulando..."
              FAILED_MODULES="$FAILED_MODULES $module"
              continue
            fi

            pushd "$module" > /dev/null

            if [[ "${{ github.base_ref }}" == "main" ]]; then
              ENV_ID="${{ env.PROD_ENVID }}"
            else
              ENV_ID="${{ env.DEV_ENVID }}"
            fi

            echo "🌍 Ambiente selecionado: $ENV_ID"

            echo "🔗 Eitri-app $module não é compartilhado. Executando 'eitri push-version'"
            if ! eitri push-version; then
              echo "❌ Falha ao executar push-version no módulo $module"
              FAILED_MODULES="$FAILED_MODULES $module"
              popd > /dev/null
              continue
            fi

            if [[ "${{ github.base_ref }}" == "develop" ]]; then
              echo "🚀 Publicando com 'eitri publish -e $ENV_ID'"
              if ! eitri publish -e $ENV_ID; then
                echo "❌ Falha ao executar publish no módulo $module"
                FAILED_MODULES="$FAILED_MODULES $module"
                popd > /dev/null
                continue
              fi
            else
              echo "⚠️ Publicação desativada, PR não é para develop."
            fi

            SUCCESSFUL_MODULES="$SUCCESSFUL_MODULES $module"

            popd > /dev/null
            echo "✅ Finalizado processamento do non-shared eitri-app: $module"
          done

          echo "======================================"
          echo "✅ Non-shared módulos processados com sucesso: $SUCCESSFUL_MODULES"
          echo "❌ Non-shared módulos que falharam: $FAILED_MODULES"
          echo "======================================"
